#!/usr/bin/env python
import sys, os

def options(opt):
    pass

def configure(cfg):
    pass

def build(bld):
    bld(
        features        = 'cxx includes',
        target          = 'systemc_config',
        export_includes = '.',
    )
