#!/usr/bin/env python
import sys, os

try:
    from waflib.extras.symwaf2ic import SYMWAF2IC_VERSION
    recurse = lambda *args, **kwargs: None
except ImportError:
    from gtest import summary
    from symwaf2ic import recurse_depends
    recurse = lambda ctx: recurse_depends(depends, ctx)

def depends(ctx):
    ctx('logger')
    ctx('hicann-system', 'units/arq')
    ctx('hicann-system', 'units/stage2_hal')
    ctx('hicann-system', 'units/jtag_lib')
    ctx('hicann-system', 'global_src/systemc')

def options(ctx):
    ctx.load('compiler_cxx')

    recurse(ctx)

def configure(ctx):
    ctx.load('compiler_cxx')

    recurse(ctx)

def build(ctx):
    recurse(ctx)

    ctx(
        target          = 'measure_inc',
        export_includes = 'source',
    )

    # build stage2 conf objects
    ctx.objects (
        target          = 'measure_obj',
        source          = 'source/MeasKeithley.cpp',
        use             = [
            'measure_inc',
            's2hal_inc',
            'systemc_config',
            'arq_obj',
            'logger_obj',
            'tud_jtag',
            'jtag_lib_obj'
            ],
        cxxflags = ['-fPIC'],
    )

