#!/usr/bin/env python
import sys, os

try:
    from waflib.extras.symwaf2ic import SYMWAF2IC_VERSION
    recurse = lambda *args, **kwargs: None
except ImportError:
    from gtest import summary
    from symwaf2ic import recurse_depends
    recurse = lambda ctx: recurse_depends(depends, ctx)

def depends(ctx):
    ctx('lib-rcf')

def options(ctx):
    ctx.load('compiler_cxx')

    recurse(ctx)

def configure(ctx):
    ctx.load('compiler_cxx')

    recurse(ctx)

def build(ctx):
    recurse(ctx)

    HOSTFPGA_FILES = [
            'source/types-fpga.c',
            'source/types-fpga.cpp',
        ]

    ctx(
        target          = 'hostfpga_inc',
        export_includes = 'source',
    )

    # build hal_backend objects
    ctx.objects(
        target          = 'hostfpga_obj',
        source          = HOSTFPGA_FILES,
        includes        = 'source',
        use             = 'rcf-sf-only hostfpga_inc',
    )
