#!/usr/bin/env python
import sys, os

try:
    from waflib.extras.symwaf2ic import SYMWAF2IC_VERSION
    recurse = lambda *args, **kwargs: None
except ImportError:
    from gtest import summary
    from symwaf2ic import recurse_depends
    recurse = lambda ctx: recurse_depends(depends, ctx)

def depends(ctx):
    ctx('logger')
    ctx('hicann-system', 'units/arq')
    ctx('hicann-system', 'units/stage2_hal')
    ctx('hicann-system', 'units/jtag_lib')
    ctx('hicann-system', 'global_src/systemc')

def get_env(env):
    try:
        return os.environ.get(env).split(os.pathsep)
    except:
        return []


def options(ctx):
    ctx.load('compiler_cxx')

    recurse(ctx)

def configure(ctx):
    ctx.load('compiler_cxx')

    recurse(ctx)

    ctx.check_cxx(
            lib          = 'xerces-c',
            includes     = get_env('CPLUS_INCLUDE_PATH'),
            libpath      = get_env('LIBRARY_PATH'),
            mandatory    = True,
            uselib_store = 'XERCES')

def build(ctx):
    recurse(ctx)

    ctx(
        target          = 's2conf_inc',
        export_includes = 'source',
        )

    # build stage2 conf objects
    ctx.objects (
        target          = 's2conf_obj',
        source          = 'source/stage2_conf.cpp',
        cxxflags        = ['-fPIC'],
        use             = [
            's2hal_inc',
            'systemc_config',
            'arq_obj',
            'tud_jtag',
            'logger_obj',
            's2conf_inc',
            'XERCES',
            ],
    )
