#!/usr/bin/env python
import sys, os

try:
    from waflib.extras.symwaf2ic import SYMWAF2IC_VERSION
    recurse = lambda *args, **kwargs: None
except ImportError:
    from gtest import summary
    from symwaf2ic import recurse_depends
    recurse = lambda ctx: recurse_depends(depends, ctx)

def depends(ctx):
    ctx('logger')

def options(ctx):
    ctx.load('compiler_cxx')

    recurse(ctx)

def configure(ctx):
    ctx.load('compiler_cxx')

    recurse(ctx)

    # arq stuff
    ctx.env.INCLUDES_ARQ_INC  = 'source'


def build(ctx):
    recurse(ctx)

    ARQ_SRCS  = [ ctx.path.find_resource('source/%s' % x) for x in [
        'timer.cpp', 'nullstream.cpp'] ]

    ctx(
        features        = 'cxx includes',
        target          = 'arq_inc',
        export_includes = ctx.env.INCLUDES_ARQ_INC,
    )

    # build stage2 conf objects
    ctx.objects (
        target          = 'arq_obj',
        source          = ARQ_SRCS,
        cxxflags        = ['-fPIC',],
        use             = [
            'logger_obj',
            'arq_inc',
            ],
    )


